// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: jwt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestParseJwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestParseJwt) Reset() {
	*x = RequestParseJwt{}
	mi := &file_jwt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestParseJwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestParseJwt) ProtoMessage() {}

func (x *RequestParseJwt) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestParseJwt.ProtoReflect.Descriptor instead.
func (*RequestParseJwt) Descriptor() ([]byte, []int) {
	return file_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *RequestParseJwt) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RequestGenToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Xh    string                 `protobuf:"bytes,1,opt,name=xh,proto3" json:"xh,omitempty"`
	// Token validity in nanoseconds. The server enforces its configured maximum.
	Valid int64 `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	// Credential associated with issuer. New issuing clients should provide it.
	IssueKey string `protobuf:"bytes,3,opt,name=issue_key,json=issueKey,proto3" json:"issue_key,omitempty"`
	// Stable identifier of the service issuing the token.
	Issuer        string `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGenToken) Reset() {
	*x = RequestGenToken{}
	mi := &file_jwt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGenToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGenToken) ProtoMessage() {}

func (x *RequestGenToken) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGenToken.ProtoReflect.Descriptor instead.
func (*RequestGenToken) Descriptor() ([]byte, []int) {
	return file_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGenToken) GetXh() string {
	if x != nil {
		return x.Xh
	}
	return ""
}

func (x *RequestGenToken) GetValid() int64 {
	if x != nil {
		return x.Valid
	}
	return 0
}

func (x *RequestGenToken) GetIssueKey() string {
	if x != nil {
		return x.IssueKey
	}
	return ""
}

func (x *RequestGenToken) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type ParseJwtResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=Valid,proto3" json:"Valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseJwtResult) Reset() {
	*x = ParseJwtResult{}
	mi := &file_jwt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseJwtResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseJwtResult) ProtoMessage() {}

func (x *ParseJwtResult) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseJwtResult.ProtoReflect.Descriptor instead.
func (*ParseJwtResult) Descriptor() ([]byte, []int) {
	return file_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *ParseJwtResult) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *ParseJwtResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type GenTokenResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenTokenResult) Reset() {
	*x = GenTokenResult{}
	mi := &file_jwt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenTokenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenTokenResult) ProtoMessage() {}

func (x *GenTokenResult) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenTokenResult.ProtoReflect.Descriptor instead.
func (*GenTokenResult) Descriptor() ([]byte, []int) {
	return file_jwt_proto_rawDescGZIP(), []int{3}
}

func (x *GenTokenResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Claims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Xh            string                 `protobuf:"bytes,2,opt,name=xh,proto3" json:"xh,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claims) Reset() {
	*x = Claims{}
	mi := &file_jwt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_jwt_proto_rawDescGZIP(), []int{4}
}

func (x *Claims) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Claims) GetXh() string {
	if x != nil {
		return x.Xh
	}
	return ""
}

func (x *Claims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

var File_jwt_proto protoreflect.FileDescriptor

const file_jwt_proto_rawDesc = "" +
	"\n" +
	"\tjwt.proto\x12\x05proto\"'\n" +
	"\x0fRequestParseJwt\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"l\n" +
	"\x0fRequestGenToken\x12\x0e\n" +
	"\x02xh\x18\x01 \x01(\tR\x02xh\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\x03R\x05valid\x12\x1b\n" +
	"\tissue_key\x18\x03 \x01(\tR\bissueKey\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\"M\n" +
	"\x0eParseJwtResult\x12%\n" +
	"\x06claims\x18\x01 \x01(\v2\r.proto.ClaimsR\x06claims\x12\x14\n" +
	"\x05Valid\x18\x02 \x01(\bR\x05Valid\"&\n" +
	"\x0eGenTokenResult\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\x06Claims\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02xh\x18\x02 \x01(\tR\x02xh\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer2\x84\x01\n" +
	"\bPassport\x12;\n" +
	"\bParseJwt\x12\x16.proto.RequestParseJwt\x1a\x15.proto.ParseJwtResult\"\x00\x12;\n" +
	"\bGenToken\x12\x16.proto.RequestGenToken\x1a\x15.proto.GenTokenResult\"\x00B\tZ\a.;protob\x06proto3"

var (
	file_jwt_proto_rawDescOnce sync.Once
	file_jwt_proto_rawDescData []byte
)

func file_jwt_proto_rawDescGZIP() []byte {
	file_jwt_proto_rawDescOnce.Do(func() {
		file_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jwt_proto_rawDesc), len(file_jwt_proto_rawDesc)))
	})
	return file_jwt_proto_rawDescData
}

var file_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jwt_proto_goTypes = []any{
	(*RequestParseJwt)(nil), // 0: proto.RequestParseJwt
	(*RequestGenToken)(nil), // 1: proto.RequestGenToken
	(*ParseJwtResult)(nil),  // 2: proto.ParseJwtResult
	(*GenTokenResult)(nil),  // 3: proto.GenTokenResult
	(*Claims)(nil),          // 4: proto.Claims
}
var file_jwt_proto_depIdxs = []int32{
	4, // 0: proto.ParseJwtResult.claims:type_name -> proto.Claims
	0, // 1: proto.Passport.ParseJwt:input_type -> proto.RequestParseJwt
	1, // 2: proto.Passport.GenToken:input_type -> proto.RequestGenToken
	2, // 3: proto.Passport.ParseJwt:output_type -> proto.ParseJwtResult
	3, // 4: proto.Passport.GenToken:output_type -> proto.GenTokenResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jwt_proto_init() }
func file_jwt_proto_init() {
	if File_jwt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jwt_proto_rawDesc), len(file_jwt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwt_proto_goTypes,
		DependencyIndexes: file_jwt_proto_depIdxs,
		MessageInfos:      file_jwt_proto_msgTypes,
	}.Build()
	File_jwt_proto = out.File
	file_jwt_proto_goTypes = nil
	file_jwt_proto_depIdxs = nil
}
